// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv8i__1IldcFZ90jWMBu3wxVuA_xTENb0',
    appId: '1:651239648591:web:ed3b7e217d78192259693a',
    messagingSenderId: '651239648591',
    projectId: 'chatify-app-2ecbc',
    authDomain: 'chatify-app-2ecbc.firebaseapp.com',
    storageBucket: 'chatify-app-2ecbc.firebasestorage.app',
    measurementId: 'G-YFFLQ8RXPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Rxll5TR6jMsdX9s5Ktm4dHdCfhuCr0A',
    appId: '1:651239648591:android:fe440270d325afe859693a',
    messagingSenderId: '651239648591',
    projectId: 'chatify-app-2ecbc',
    storageBucket: 'chatify-app-2ecbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTZm3CEwOluE96W5Ckb39vCvQFasZnL0',
    appId: '1:651239648591:ios:84991117077fa5d959693a',
    messagingSenderId: '651239648591',
    projectId: 'chatify-app-2ecbc',
    storageBucket: 'chatify-app-2ecbc.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCTZm3CEwOluE96W5Ckb39vCvQFasZnL0',
    appId: '1:651239648591:ios:84991117077fa5d959693a',
    messagingSenderId: '651239648591',
    projectId: 'chatify-app-2ecbc',
    storageBucket: 'chatify-app-2ecbc.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv8i__1IldcFZ90jWMBu3wxVuA_xTENb0',
    appId: '1:651239648591:web:6f928f702facb96d59693a',
    messagingSenderId: '651239648591',
    projectId: 'chatify-app-2ecbc',
    authDomain: 'chatify-app-2ecbc.firebaseapp.com',
    storageBucket: 'chatify-app-2ecbc.firebasestorage.app',
    measurementId: 'G-YG2EZBV8YZ',
  );
}
